query Me {
    me {
        id
        bankAccounts  {
            name
            id
            bank {
                id
                swiftCode
                name
                icon {
                    url
                }
            }
            bankId
            number
        }
    }
}
